web/Auth/BricksAndHeartsUser.cs, web/Controllers/AdminController.cs, web/Services/AdminService.cs, web/Views/Admin/Index.cshtml
If a user has requested admin access, they can now cancel this request. A confirmation message appears when this is successful.
=> BNH-3 Add button to cancel admin rights request

web/Views/Landlord/Register.cshtml
=> BNH-35 feat: removed unwanted line from landlord registry page.

web/Views/Admin/AdminList.cshtml
Removed duplicate class tag in tables so that the bootstrap styling worked. Also added col tags to define the column headers better.
=> BNH-36 Admin List table styling

web/Services/LandlordService.cs, web/Views/Landlord/Register.cshtml, web/wwwroot/js/site.js
Sign up was previously passing a null value for landlord type as it wasn't updated inside the landlord service file. This is now fixed.
=> BNH-16 bug fix: didn't allow users to sign up

web/Views/Landlord/Properties.cshtml
Some minimal styling, added postcode to properties and removed extra commas between whitespace depending on if a line 2 and 3 are present in the address
=> BNH-64 property table styling

web/Views/Property/AddNewProperty.cshtml
The add new property form now has a back link which takes you to the previous step
=> BNH-70 Add 'Back' link to Add New Property form

BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs, BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTestsBase.cs, web/Controllers/PropertyController.cs, web/Services/PropertyService.cs, web/Views/Landlord/Properties.cshtml, web/Views/Property/ViewProperty.cshtml
Properties can be deleted from the individual view page. Confirmation is required so that they are not deleted accidentally.
=> Bnh 41: delete property

web/Database/PropertyDbModel.cs, web/Migrations/20220803085715_AddTenantProfileToProperty.Designer.cs, web/Migrations/20220803085715_AddTenantProfileToProperty.cs, web/Services/PropertyService.cs, web/ViewModels/AddNewPropertyViewModel.cs, web/ViewModels/PropertyViewModel.cs, web/Views/Property/AddNewProperty.cshtml, web/Views/Property/_AddFormStep1.cshtml, web/Views/Property/_AddFormStep2.cshtml, web/Views/Property/_AddFormStep4.cshtml, web/Views/Property/_AddFormStep5.cshtml, web/Views/Property/_AddFormStep6.cshtml, web/wwwroot/css/site.css
- Letting profile fields have been added to the property form
- Reordered a few of the pages
- Currently unstyled so we can style the whole form together once the design is finalised
- Added some CSS classes for future pill-like radio-checkbox inputs
=> BNH-82 Add letting profile fields to properties

web/ViewModels/PropertyViewModel.cs, web/Views/Property/ViewProperty.cshtml, web/Views/Property/_AddFormStep5.cshtml
Changes made as a result of testing:
- "Allow pets" radio input is now a required field (you have to choose yes or no)
- Display letting profile on a property's page (looks quite crude, waiting for styling)
=> BNH-82 Letting profile

web/Views/Shared/_RegisterPagePartial.cshtml, web/wwwroot/css/site.css
Added basic css variables for colours, styled a couple of buttons
=> BNH-91 colours

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs, web/Controllers/LandlordController.cs, web/Services/LandlordService.cs, web/ViewModels/LandlordProfileModel.cs, web/ViewModels/PropertiesDashboardViewModel.cs, web/Views/Landlord/Properties.cshtml
Little fix to name the landlord whose properties are being displayed. 
Fixed thanks to Alice's feedback on the ticket while testing.
=> BNH-48_fix feat: Names landlord on property list

web/Views/Shared/_Layout.cshtml, web/wwwroot/css/site.css
Imported fonts and added custom classes for each of the font categories shiv designed, applied the base font to everything
=> BNH-92 fonts

web/Views/Shared/_Layout.cshtml, web/wwwroot/css/site.css
- Added secondary navbar for landlords/admins
- Styled navbars to match designs
- Moved privacy and contact links to footer
=> BNH-88 Update navbar and footer

web/Views/Home/Index.cshtml
Also style it to look less bad on large screens
=> Fix typo on home page text

BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs, web/Controllers/PropertyController.cs, web/Services/AzureStorage.cs, web/ViewModels/ImageListViewModel.cs, web/Views/Property/ListPropertyImages.cshtml, web/Views/Property/ViewProperty.cshtml, web/wwwroot/css/site.css
There is a test that is not working since it involves url.action()
=> Bnh 90 display images

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandLordControllerUnassignedTests.cs, web/Controllers/LandlordController.cs, web/Services/MailService.cs, web/Views/Shared/_Layout.cshtml, web/appsettings.json
Hopefully this will have fixed the issue with the MailService causing test failures.
=> BNH-111 fix: move TrySendMsg into MailService

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs, BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs, BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs, BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs, web/Controllers/AdminController.cs, web/Database/BricksAndHeartsDbContext.cs, web/Database/TenantDbModel.cs, web/Migrations/20220808104842_AddTenantTable.Designer.cs, web/Migrations/20220808104842_AddTenantTable.cs, web/Migrations/20220808112642_AlterTenantProperties.Designer.cs, web/Migrations/20220808112642_AlterTenantProperties.cs, web/Services/AdminService.cs, web/ViewModels/TenantListModel.cs, web/Views/Admin/TenantList.cshtml, web/Views/Shared/_Layout.cshtml
Added a tenant table to the database, and a TenantList page to display this information:
=> BNH 115 - tenant table

BricksAndHearts.UnitTests/ServiceTests/Property/PropertyServiceTests.cs, BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs, web/Database/PropertyDbModel.cs, web/Migrations/20220808092458_AddPropertyAvailability.Designer.cs, web/Migrations/20220808092458_AddPropertyAvailability.cs, web/Services/PropertyService.cs, web/ViewModels/PropertyCountModel.cs, web/ViewModels/PropertyViewModel.cs, web/Views/Admin/AdminDashboard.cshtml, web/Views/Admin/PropertyList.cshtml, web/Views/Landlord/Properties.cshtml, web/Views/Landlord/_RegisterPagePartial.cshtml, web/Views/Property/ViewProperty.cshtml, web/Views/Property/_AddFormStep6.cshtml, web/wwwroot/js/site.js
Availability and AvailableFrom added to property database; this information is displayed in appropriate pages of the website.
=> BNH-40 - property availability state

BricksAndHearts.UnitTests/ServiceTests/Property/PropertyServiceTests.cs, BricksAndHearts.UnitTests/ServiceTests/Property/PropertyServiceTestsBase.cs, BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs
Encased each method's tests in a region for organisation
=> BNH-77 feat: Added tests for all current methods in propertyService

web/Views/Property/AddNewProperty.cshtml, web/Views/Property/_AddFormStep1.cshtml, web/Views/Property/_AddFormStep2.cshtml, web/Views/Property/_AddFormStep3.cshtml, web/Views/Property/_AddFormStep4.cshtml, web/Views/Property/_AddFormStep5.cshtml, web/Views/Property/_AddFormStep6.cshtml, web/Views/Shared/_Layout.cshtml, web/wwwroot/css/site.css
Applied styling to the property form to match the designs. There are still fields in the designs which we don't have, but this is just a front-end change for now
Screenshots show the major changes:
=> BNH-103 Style property form

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTestsBase.cs, BricksAndHearts.UnitTests/ServiceTests/Landlord/LandlordServiceTests.cs, BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs, web/Controllers/LandlordController.cs, web/Database/LandlordDbModel.cs, web/Migrations/20220809171109_AlterCharterStatusFields.Designer.cs, web/Migrations/20220809171109_AlterCharterStatusFields.cs, web/Services/LandlordService.cs, web/ViewModels/LandlordProfileModel.cs, web/Views/Admin/LandlordList.cshtml, web/Views/Landlord/_RegisterPagePartial.cshtml, web/Views/Property/_AddFormStep6.cshtml, web/wwwroot/js/site.js
Charter status has been simplified to use `membershipId` to test if the landlord has completed the charter, and the `CharterApproved` bool for determining if it's been approved.
Also check membership ID for duplicates when approving
=> BNH-114 Charter approval membership ID field

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs, BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs, BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs, web/Controllers/AdminController.cs, web/Services/AdminService.cs, web/ViewModels/TenantListModel.cs, web/Views/Admin/TenantList.cshtml
Created filters for the tenant list.
The user can select multiple filters which all stack on top of each other to refine the tenant list
=> BNH-119 tenant filtering

BricksAndHearts.UnitTests/BricksAndHearts.UnitTests.csproj, BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs, BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs, BricksAndHearts.UnitTests/ServiceTests/CsvImport/CsvImportServiceTests.cs, web/BricksAndHearts.csproj, web/Controllers/AdminController.cs, web/Program.cs, web/Services/AdminService.cs, web/Services/CsvImportService.cs, web/ViewModels/TenantUploadModel.cs, web/Views/Admin/TenantList.cshtml, web/wwwroot/TenantImportCSVTemplate.csv
Unit tests for this to follow shortly - I anticipate there will be things which need changing on this branch, so wanted to open a pull request to allow you an initial look through.
=> BNH-116 - Import tenant data from CSV file

web/Controllers/AdminController.cs, web/Views/Landlord/Profile.cshtml, web/wwwroot/js/site.js
=> BNH-123 invite link displays properly and has a copy button

web/Controllers/AdminController.cs, web/Controllers/HomeController.cs, web/Services/AdminService.cs, web/wwwroot/js/site.js
Applied some changes from Oskar, used this() to await an async javascript function, small amount of refactoring such as changing lets to consts and multilining some long code
=> BNH-123 Fix/neatening

BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs, web/Services/AdminService.cs
I think it's a good idea and Emily isn't here to tell me off
=> Fastest admin first

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs, BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs, web/Controllers/AdminController.cs, web/Database/TenantDbModel.cs, web/Services/AdminService.cs, web/Views/Admin/AdminList.cshtml
Admins can remove other admins through the admin lists; admins cannot revoke their own admin status.
=> BNH-125 - Remove admins

.github/workflows/main_bricks-and-hearts-stg.yml
Add in environment to deploy live step
=> BNH-NONE: Attempt to set up gated deploy using github environments

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs, BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs, BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs, BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTestsBase.cs, web/Controllers/AbstractController.cs, web/Controllers/AdminController.cs, web/Controllers/LandlordController.cs, web/Controllers/PropertyController.cs, web/Services/CsvImportService.cs, web/Views/Admin/TenantList.cshtml, web/Views/Property/ListPropertyImages.cshtml, web/Views/Shared/_Layout.cshtml
Refactored the flash messages so that there is a single method, dealing with single and multiple flash messages.
=> BNH-129 - refactor flash messages

web/Views/Property/ViewProperty.cshtml
passed in property id to edit property after it went missing during the changes in BNH-137 somehow
=> BNH-143 fix: edit page from property view broken

web/Controllers/LandlordController.cs, web/Views/Landlord/Register.cshtml, web/Views/Shared/_Layout.cshtml
If an Admin tries to sign themselves up as a landlord, the landlord registration page has a warning flash message:
=> BNH-146 - warn if admin tries to become landlord

web/Views/Admin/AdminDashboard.cshtml, web/Views/Shared/_DashboardStatsBoxPartial.cshtml, web/wwwroot/css/site.css
A few small changes to the Admin Dashboard styling, based on Max's comments on BNH-151.
=> BNH-173 - further Admin Dashboard styling

web/Views/Landlord/Register.cshtml, web/Views/Landlord/_RegisterPagePartial.cshtml, web/Views/Property/AddNewProperty.cshtml, web/wwwroot/css/site.css, web/wwwroot/js/registerPageScript.js
Just front-end tweaks to the landlord registration form to match the designs
=> BNH-138 Style landlord registration form

web/Services/PropertyService.cs, web/Views/Shared/_Layout.cshtml
Fix for bug discovered during testing
=> BNH-162 Fix for public property link

web/Controllers/AdminController.cs, web/ViewModels/PaginationModel.cs, web/Views/Admin/LandlordList.cshtml, web/Views/Admin/PropertyList.cshtml, web/Views/Admin/TenantList.cshtml, web/Views/Admin/_TenantImportModal.cshtml, web/Views/Admin/_TenantTable.cshtml, web/Views/Landlord/Properties.cshtml, web/Views/Shared/_PaginationPartial.cshtml
- Styled table to match designs
- Moved CSV upload into a modal
- Add `TypeOfData` property to pagination
- Sort and filter will be combined in #151
=> BNH-156 Style tenant list page

web/Views/Property/PropertyInputForm/_PropertyFormButtons.cshtml
Buttons now say "submit" if clicking it would not lead to another form page.
=> BNH-181 feat: Form buttons now say "submit" if clicking it would not lead to another form page.

web/Views/Admin/LandlordList.cshtml, web/Views/Admin/_LandlordTable.cshtml
Applied styling to match designs
=> BNH-153 Style landlord list

web/Views/Admin/AdminList.cshtml, web/wwwroot/css/site.css
- Style the admin list to match other table pages
- Combined the current and pending tables into one
=> BNH-183 Style admin list

web/Controllers/PropertyController.cs, web/ViewModels/PropertyInput/PropertyInputModelAvailability.cs, web/ViewModels/PropertyInput/PropertyInputModelTenantPreferences.cs, web/Views/Property/PropertyInputForm/Availability.cshtml, web/wwwroot/js/site.js
-Datepicker now only shows date and not time
-Datepicker now correctly shows when AvailableSoon is selected
-User is only required to enter a date on step six if AvailableSoon is selected
-User may only choose a future date client side.
-Server side, both validation rules above are enforced
-Fixed an issue with server side invalid model redirects for steps 3-5 always redirecting to step 2
=> BNH-180: Fixes surrounding availability datepicker

web/Views/Shared/Details/_TenantPreferences.cshtml
fixed some incorectly coloured icons/text on the propertydisplaypartial
=> BNH-163 fix wrongly coloured icons:

web/ViewModels/PropertyInput/PropertyInputModelAvailability.cs, web/Views/Property/PropertyInputForm/Availability.cshtml
Now requires the Available From date to be in the future not the present or future. Both server side and client side.
=> BNH-198 fix: Available From should be future only, not future or present

web/ViewModels/LandlordProfileModel.cs, web/Views/Landlord/_RegisterPagePartial.cshtml, web/wwwroot/js/registerPageScript.js, web/wwwroot/js/site.js
The landlord Title dropdown, and Title (other) box, now populate with the correct information when the Title is non-standard. Also, this non-standard title will display on the Review page (as opposed to simply other).
The Title (other) box only appears on first loading the edit form if the existing title is in the category Other.
=> BNH-191 - Landlord Title fix

web/Views/Admin/_MatchListPropertyViewPartial.cshtml, web/Views/Property/Details/_Details.cshtml, web/Views/Property/PublicViewProperty.cshtml, web/Views/Property/ViewProperty.cshtml
fixed not available yet floating to the right and other minor style changes, e.g. read more button on description.
=> BNH-163 match page restyle

web/Controllers/LandlordController.cs, web/Controllers/PropertyController.cs, web/ViewModels/PropertyListModel.cs, web/Views/Admin/PropertyList.cshtml, web/Views/Property/_PropertyTable.cshtml, web/wwwroot/css/site.css, web/wwwroot/js/site.js
Updated property table to reflect feedback from UAT.
- Refactored `PropertyListModel` to have a list of `PropertyDetailsModel`s so we can access images and landlord data
- Added images to property table
- Changed description to hide overflow and link to details page to read all of it
- Changed "View" buttons to "View/Edit"
=> BNH-189 Property table restyling

web/Views/Home/Index.cshtml, web/wwwroot/css/site.css
=> BNH-199: Made login box scaleable on mobile

web/Views/Landlord/_DashboardPropertyDisplayPartial.cshtml
added a read more to landlord dashboard to prevent excessively long messages
=> BNH-201 landlord dashboard description

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs, BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs, web/Controllers/AdminController.cs, web/Controllers/LandlordController.cs, web/Views/Landlord/Dashboard.cshtml, web/Views/Landlord/Profile.cshtml, web/Views/Shared/_Layout.cshtml, web/wwwroot/js/site.js
Fixed up a few edge cases in routing from testing feedback. Pages now shouldn't show any landlord/property IDs in the URL query string.
=> BNH-193 Routing

web/Views/Landlord/Profile.cshtml
The "view properties" button on the landlord profile will take you to `/landlord/{id}/properties` if you're an admin, and `/landlord/me/properties` if you're a landlord. The admin behaviour overrides the landlord behaviour if you're both.
=> BNH-193 Routing bug fix

web/Controllers/TenantController.cs
email formatting had gone away during a rebase at some point! Now it's back
=> BNH-162 fix: readded lost email formatting

web/Views/Landlord/Profile.cshtml
fixing a dumb bug that I missed last time
=> BNH-193 I hate routing

web/Views/Landlord/_RegisterPagePartial.cshtml, web/wwwroot/js/registerPageScript.js
Coloured the * red and added a line of text explaining that * denotes a compulsory field.
Also, fixed a minor bug in the form submission: it was previously clearing the review tab from the view before actually submitting the form, causing a noticeable change directly before submission.
=> BNH-204 - required registration fields styling (landlord form)

web/Views/Admin/_MatchListPropertyViewPartial.cshtml, web/wwwroot/css/site.css
removed image hover and aligned image with property title
=> BNH-163 match page styling

DATABASE_UNIT_TESTS.MD, README.md
- Updated readme with all the useful setup information from the Swiki space
- Copied over the database unit testing guide
- Merged in Ben's copyright notice branch
=> BNH-184 Update README

BricksAndHearts.UnitTests/ServiceTests/Property/PropertyServiceTests.cs, web/Controllers/PropertyController.cs, web/ViewModels/PropertyInput/PropertyInputModelAvailability.cs, web/ViewModels/PropertyInput/PropertyInputModelDescription.cs, web/ViewModels/PropertyInput/PropertyInputModelDetails.cs, web/Views/Property/PropertyInputForm/Availability.cshtml, web/Views/Property/PropertyInputForm/Description.cshtml, web/Views/Property/PropertyInputForm/Details.cshtml, web/Views/Property/PropertyInputForm/FullAddress.cshtml, web/Views/Property/PropertyInputForm/InitialAddress.cshtml, web/Views/Property/PropertyInputForm/TenantPreferences.cshtml, web/Views/Property/PropertyInputForm/_LayoutPropertyInputForm.cshtml, web/Views/Property/ViewProperty.cshtml, web/Views/Property/_PropertyTable.cshtml, web/wwwroot/js/site.js
- Rent now appears with property details so the edit button makes sense
- Added button to edit address
- Added radio for single/multiple units and input for number of occupied units
- Added instructions to description
- Added asterisks
=> BNH-203, 190 and 196 Property form frontend changes

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandLordControllerUnassignedTests.cs, web/Controllers/LandlordController.cs, web/Controllers/TenantController.cs, web/Views/Admin/AdminDashboard.cshtml, web/Views/Home/Index.cshtml, web/Views/Landlord/Invite.cshtml, web/Views/Landlord/Profile.cshtml, web/Views/Landlord/_RegisterPagePartial.cshtml, web/Views/Property/PublicViewProperty.cshtml, web/Views/Shared/_Layout.cshtml, web/wwwroot/css/site.css, web/wwwroot/js/site.js
Added modal with a brief explanation of what the 'Invite link' functionality is (this caused confusion during UAT).
Restyled the buttons on the page to make them equally-sized and more distinguished from each other.
Fixed a minor formatting bug with the profile picture overlapping with the name/profile type on smaller screens.
=> BNH-192 - landlord profile restyling

web/Views/Landlord/Dashboard.cshtml, web/Views/Landlord/_DashboardPropertyDisplayPartial.cshtml, web/Views/Shared/_DashboardStatsBoxPartial.cshtml
=> BNH-208 Improve spacing on landlord dashboard

web/ViewModels/StatBoxModel.cs, web/Views/Landlord/Dashboard.cshtml, web/Views/Landlord/_DashboardPropertyDisplayPartial.cshtml, web/Views/Shared/_DashboardStatsBoxPartial.cshtml
- Hopefully fixed all the spacing issues now
- Made the charter approval text slightly smaller
=> BNH-208 Further styling
