Change-Ahead/bricks-and-hearts

web/Views/Admin/AdminList.cshtml
web/wwwroot/css/site.css

Admin and pending admin lists now have equal widths to each other at all window dimensions.

BNH-36 fix

---

.github/workflows/test_on_push_bricks-and-hearts.yml
BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs
BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs
BricksAndHearts.UnitTests/ServiceTests/TestDbContext.cs
BricksAndHearts.UnitTests/TestDbContext.cs
web/appsettings.json

- Created a framework for unit testing our database operations found in the Service classes, following [this guide](https://docs.microsoft.com/en-us/ef/core/testing/testing-with-the-database) from the Entity Framework docs
- This uses a new `BricksAndHeartsTest` database
- This can test read and write operations, and uses a non-committing transaction to maintain isolation between tests
- The pull request GitHub Action has been updated to now run an instance of SQL Server, which is used when these tests are run for pull requests
- Added a small number of example tests for `AdminService` to demonstrate how this should be used
> Following [EF's advice](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy), I've experimented with using a production test database for …

BNH-61 Unit tests for database methods

---

web/appsettings.json

As noted on [the ticket](https://softwiretech.atlassian.net/browse/BNH-12?atlOrigin=eyJpIjoiZmE3YmRmZTM2MDc5NDlkZTg4YTEyNTMwOTUxNjMyYWYiLCJwIjoiaiJ9), the `appsettings.json` was missing some fields required to send emails, which caused an unhandled exception during landlord registration on the staging site.
The fields have been added and tested successfully locally. The password has been added to Azure's application settings.

BNH-12 Fix landlord registration exception caused by email

---

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTestsBase.cs
web/Controllers/AdminController.cs
web/Controllers/LandlordController.cs
web/Database/LandlordDbModel.cs
web/Migrations/20220722110224_AddCharterApprovalDetails.Designer.cs
web/Migrations/20220722110224_AddCharterApprovalDetails.cs
web/Services/LandlordService.cs
web/ViewModels/LandlordProfileModel.cs
web/Views/Landlord/Profile.cshtml

When an admin views the profile page of an unapproved landlord, beneath the 'Charter Status' heading there will be a button to 'Approve Landlord'. This does not appear when the current user is not an admin or when the landlord is already approved.
When clicked, this button changes some entries in the appropriate row of the Landlord table in the database: CharterApproved becomes 'true', ApprovalTime sets to the current DateTime and ApprovalAdminId set to the Id of the current user.
[THERE ARE DATABASE MIGRATIONS IN THIS PULL REQUEST]
Profile page view with button (only change is under 'Charter Status' heading

BNH-21 - approve landlords

---

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTestsBase.cs
web/Controllers/LandlordController.cs

Admins can now edit landlord profiles by clicking / typing in the route in a similar way to navigating to the profiles. Also added a check that the profile passed into the edit method is properly defined. Wrote additional unit tests.

BNH-45 Admin edit landlord profile

---

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTestsBase.cs
web/Controllers/LandlordController.cs
web/Services/LandlordService.cs
web/Views/Landlord/Profile.cshtml

When an admin approves the charter of a landlord, the landlord's profile reloads with a message indicating that either
- the charter has been successfully approved (in which case database changes will also have occurred)
- the charter was previously approved
- the landlord does not appear to exist (the image below was generated by temporarily hard-coding an error)

BNH-72 - success/failure message for charter approval

---

.editorconfig

Added an editorconfig file which should update code styling rules through github. I've worked out most issues through the last couple of pull requests, but might be worth having a look over in your editor to check there's nothing egregiously wrong. :)
People will have to combine this with the advice on my swiki page of doing a code cleanup on save, I believe? 
https://softwiretech.atlassian.net/wiki/spaces/IP22/pages/20184563758/Automatic+Code+Clean+Up+and+Formatting

BNH-85 feat: Enforcing code style

---

web/wwwroot/js/registerPageScript.js

Reset local storage to default after use so that the next time you go to a page it is the default page unless otherwise specified, changed the enter keylistener to keydown instead of keyup to prevent the page being moved on when typing into the address bar

BNH-87 fixing BNH-17: edit page tabbing wrong

---

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs
web/Controllers/LandlordController.cs
web/Database/LandlordDbModel.cs
web/Migrations/20220802124217_AddMembershipId.Designer.cs
web/Migrations/20220802124217_AddMembershipId.cs
web/Services/LandlordService.cs
web/ViewModels/LandlordProfileModel.cs
web/Views/Landlord/Profile.cshtml
web/Views/Shared/_RegisterPagePartial.cshtml
web/wwwroot/js/registerPageScript.js
web/wwwroot/js/site.js

Adds Membership Id to the landlord registration and edit forms as a field which is displayed and required only if the Charter Status 'Already Approved' is selected (LandlordProvidedCharterStatus==true); otherwise, any input into the MembershipId field is ignored.
MembershipId is displayed in the ChangeAhead Charter section of the profile, if it has been provided; the button to 'Confirm Landlord Charter Membership' for Pending landlords only appears if there is a membership Id. Currently, however, the database will allow landlords without a Membership Id to be in an approved state - this is just not possible by following links through the website.

BNH 80 - add membershipId

---

BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTestsBase.cs
web/Controllers/PropertyController.cs
web/Services/AzureStorage.cs
web/Services/PropertyService.cs
web/Views/Property/ListPropertyImages.cshtml
web/wwwroot/css/site.css

BNH-94: The issue was that when filenames contained spaces, the image wouldn't display. This turned out not to be due to Azure's naming conventions (which are reasonably standard for files) but due to the space being treated as a string delimiter. I have fixed this accordingly (there were some "" missing!).
BNH-95: Added server-side validation of the file type. Currently only JPG, JPEG, PNG, BMP and GIF will be accepted. If there are any other image types which are common enough to be needed, they can easily be added.
I also added some flash messages to indicate successful upload or failed upload due to empty/ non-image file.

Bnh 94&95 - bug fixes on image upload

---

web/Views/Home/ContactUs.cshtml
web/wwwroot/css/site.css

Removed underline from icon links.
Links open in new tab, including changeahead website.
Added the missing tab title in for the contactus page.
The other change in the BNH-98 ticket (View properties -> Properties) max did as part of his Navbar changes/styling ticket so I didn't do it here.

BNH-98: Social media links on contactus open in new tabs

---

web/ViewModels/LandlordProfileModel.cs
web/Views/Landlord/Profile.cshtml

Branched from BNH-48_Fix #92 to ensure it tidies up the references to admin status in there too, this is in response to Ben's comment on that pull request :)

BNH-48_Fix_2: Removing user's admin credentials from LandlordProfileModel

---

BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs
web/Controllers/AbstractController.cs
web/Controllers/LandlordController.cs
web/Controllers/PropertyController.cs
web/Services/AzureStorage.cs
web/Views/Property/ListPropertyImages.cshtml

Multiple flash messages can now appear on the Image List page - one per file when multiple files are uploaded simultaneously.

BNH-108 feat: display multiple flash messages

---

web/Views/Shared/_Layout.cshtml

Hacky fix because the footer is `position: absolute` so it merges with the container div

Add padding to bottom of layout container

---

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs
BricksAndHearts.UnitTests/ServiceTests/Landlord/LandlordServiceTests.cs
web/Controllers/LandlordController.cs
web/Services/LandlordService.cs
web/Views/Landlord/Profile.cshtml

Admins can set/change a landlord's charter membership ID when approving them.

BNH-114 Set membership ID when approving charter

---

BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTestsBase.cs
BricksAndHearts.UnitTests/ServiceTests/Property/PropertyServiceTests.cs
BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs
web/Database/BricksAndHeartsDbContext.cs
web/Database/PropertyDbModel.cs
web/Migrations/20220809110124_AddMultipleUnitsToAProperty.Designer.cs
web/Migrations/20220809110124_AddMultipleUnitsToAProperty.cs
web/Services/PropertyService.cs
web/ViewModels/AvailabilityState.cs
web/ViewModels/PropertyViewModel.cs
web/Views/Landlord/Properties.cshtml
web/Views/Property/ViewProperty.cshtml
web/Views/Property/_AddFormStep6.cshtml
web/wwwroot/js/site.js

- Added `TotalUnits` and `OccupiedUnits` to Property table to track how many properties are contained in each listing, and how many of these are occupied
- `TotalUnits` defaults to 1, `OccupiedUnits` defaults to 0
- SQL check constraint enforces `OccupiedUnits <= TotalUnits`
- Overall property keeps its availability states, but is forced into the Occupied state if all its units are occupied (i.e. `OccupiedUnits == TotalUnits`)
- Any future work which alters `TotalUnits` or `OccupiedUnits` in a different method should make sure the above holds, but the `UpdateProperty` method will likely be sufficient
- Number of available units is calculated as `TotalUnits - OccupiedUnits`

BNH-120 Multiple properties per listing

---

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandLordControllerUnassignedTests.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTestsBase.cs
BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTestsBase.cs
BricksAndHearts.UnitTests/ServiceTests/Property/PropertyServiceTests.cs
BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs
web/Controllers/LandlordController.cs
web/Controllers/PropertyController.cs
web/Database/LandlordDbModel.cs
web/Migrations/20220810130152_AddAddressToLandlord.Designer.cs
web/Migrations/20220810130152_AddAddressToLandlord.cs
web/Services/LandlordService.cs
web/ViewModels/AddressModel.cs
web/ViewModels/LandlordProfileModel.cs
web/ViewModels/PropertyViewModel.cs
web/Views/Landlord/Profile.cshtml
web/Views/Landlord/_RegisterPagePartial.cshtml

- Landlords now have an address!
- `PropertyAddress` has been refactored to be `AddressModel` and is shared by properties and landlords
- The address has been added to the landlord register form (mostly at random as this form will be restyled in the future)
- The landlord profile page now displays their address instead of a placeholder, and the corresponding edit button is now functional

BNH-97 Add address to landlord

---

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs
BricksAndHearts.UnitTests/ControllerTests/ControllerTestsBase.cs
BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs
web/Controllers/AdminController.cs
web/Services/AdminService.cs
web/Views/Admin/PropertyList.cshtml
web/Views/Landlord/Properties.cshtml

I've added unit tests for all the endpoints in the Admin Controller. I've also done some minor refactoring in the Admin Controller, and to a lesser extent the Admin Service - this was primarily just changing the order in which the endpoints/methods appear, in order to group together ones which are to do with similar issues. I've been finding it increasingly difficult to work out if a relevant method already exists or not, since everything was a bit jumbled up - hopefully having re-ordered things slightly will make this easier for everyone.

BNH-127 - add AdminControllerTests

---

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs
web/Controllers/LandlordController.cs

If `ModelState` is not valid when editing a landlord, we now return to the form instead of resulting in a 404.

BNH-97 fix: Return View instead of 404 when invalid model for edit

---

web/Controllers/LandlordController.cs
web/Services/LandlordService.cs
web/Views/Landlord/_RegisterPagePartial.cshtml
web/wwwroot/js/site.js

When editing a landlord, if the charter status is changed from "Already approved" to "Not yet approved" we clear the membership ID input (which is hidden at this point).
Additionally, when a landlord is edited and the membership ID is set to null (or is already null), we un-approve the landlord's charter.

BNH-114 fix: Clear membership ID field

---

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs
BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs
web/Controllers/AdminController.cs
web/Migrations/BricksAndHeartsDbContextModelSnapshot.cs
web/Services/AdminService.cs
web/ViewModels/LandlordListModel.cs
web/ViewModels/TenantListFilter.cs
web/ViewModels/TenantListModel.cs
web/Views/Admin/LandlordList.cshtml
web/Views/Admin/TenantList.cshtml

Added filters to the Landlord List so that admins can filter the list by assigned/unassigned, as well as by approved/unapproved. In the process of doing so, I discovered a mostly redundant endpoint for the TenantList, so I've changed this slightly.
Also added a button to the Landlord List for admins to Create Unassigned Landlords.

BNH-63 - unassigned landlord list

---

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandLordControllerUnassignedTests.cs
BricksAndHearts.UnitTests/ServiceTests/Admin/AdminServiceTests.cs
web/Controllers/AdminController.cs
web/Controllers/LandlordController.cs
web/Services/AdminService.cs
web/Services/MailService.cs
web/ViewModels/TenantMatchListModel.cs
web/Views/Admin/PropertyList.cshtml
web/Views/Admin/TenantList.cshtml
web/Views/Admin/TenantMatchList.cshtml
web/Views/Property/ViewProperty.cshtml

Added a simple matching "algorithm" according to the filters we have for tenant sorting. Once the tenant distance ticket is done, this can be sorted by distance (currently sorted by name). Added 2 buttons to get to this page, one from the admin property table and one from the individual property page but only if the user is an admin.
Also slightly simplified / refactored the filtering to be more in line with the landlord's requirements. Previously, all filters were exclusive (i.e. having 2 filters on showed the intersection of those 2 filters. Now filters are inclusive for the landlord type (i.e. shows the union of those 2 filters) and exclusive for everything not landlord type based on the filter page, and are inclusive everywhere for the matching algorithm.

BNH 143: Simple matching algorithm

---

BricksAndHearts.UnitTests/ControllerTests/HomeControllerTests/HomeControllerTests.cs
BricksAndHearts.UnitTests/ControllerTests/HomeControllerTests/HomeControllerTestsBase.cs
web/Controllers/HomeController.cs
web/ViewModels/HomeViewModel.cs
web/Views/Home/Index.cshtml
web/wwwroot/css/site.css

Added redirection to Index so that landlords/admins are displayed the relevant dashboard (admin takes priority, in the case where a user is both). Restyled the Home page for logged-out users and users who are neither landlords nor admins.
Figma design:
View for logged-in users:
View for logged-out users:

BNH-109 - Homepage Restyling

---

BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs
web/Controllers/PropertyController.cs

Two small fixes in the property deletion code:
BNH-164: when a property is deleted, the container on Azure Blob Storage which holds the images for that property is also deleted (to avoid storage of unneeded, and mostly inaccessible, files)
BNH-93: deleting a property which did not exist (e.g .by having the same property open in two tabs and deleting it in one tab, then attempting to in the other) was returning a (browser) 405 error - why it was 405, not 404, is slightly unclear. It now returns the user to the list of their properties (if a landlord), admin dashboard (if non-landlord admin) or home page (if nothing important), with a flash message informing them the property does not exist.

BNH-164 & 93 - property deletion

---

web/Controllers/LandlordController.cs
web/Controllers/PropertyController.cs
web/Views/Admin/PropertyList.cshtml
web/Views/Landlord/Properties.cshtml
web/Views/Property/Details/_AvailabilityPill.cshtml
web/Views/Property/ViewProperty.cshtml
web/Views/Property/_PropertyTable.cshtml
web/Views/Shared/_Layout.cshtml
web/wwwroot/css/site.css

- Admin and landlord property lists now share a partial for the table itself
- Table styled to match designs
- On mobile, table is scrollable
- To make the wide tables fit, we change from a `container` to a `container-fluid` for pages which have `TempData["Wide"]` set to `true`
Landlord:
Admin:
Landlord mobile:

BNH-141 Style property tables

---

BricksAndHearts.UnitTests/ControllerTests/Admin/AdminControllerTestsBase.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTestsBase.cs
web/Controllers/AbstractController.cs
web/Controllers/AdminController.cs
web/Views/Shared/_Layout.cshtml

AddFlashMessages method changed to be very specific about data types at every possible stage - avoiding confusion between List<string> and string[] seems to be the solution to avoiding the flash message-related errors we've had today.
Also, added a close button to flash messages.

BNH-171 - fix flash messages

---

web/Views/Landlord/EditProfilePage.cshtml
web/Views/Landlord/Profile.cshtml
web/wwwroot/js/registerPageScript.js

The edit landlord form was missing a "back" link (as reported in [BNH-195](https://softwiretech.atlassian.net/browse/BNH-195)). This has been added back in again, as well as a few minor styling improvements.

BNH-195 Add missing back button for edit landlord profile form

---

web/Services/LandlordService.cs
web/ViewModels/LandlordProfileModel.cs
web/Views/Admin/PropertyList.cshtml
web/Views/Admin/_LandlordTable.cshtml
web/Views/Landlord/_RegisterPagePartial.cshtml
web/Views/Property/PropertyInputForm/Availability.cshtml
web/wwwroot/js/registerPageScript.js
web/wwwroot/js/site.js

A few minor changes:
- asterisks added to show which fields are compulsory (and optional labels therefore removed)
- text added to Address page to instruct landlords to provide personal address (rather than business or property)
Both those changes visible on this page:
- the 'title' dropdown now has an 'Other' option, which brings up a text box in which the user enters their desired title. This is a compulsory field if and only if 'Other' has been selected.

BNH-191 - landlord registration changes

---

BricksAndHearts.UnitTests/ControllerTests/HomeControllerTests/HomeControllerTests.cs
web/Controllers/AdminController.cs
web/Controllers/HomeController.cs
web/Controllers/LandlordController.cs
web/Controllers/LoginController.cs
web/Controllers/PropertyController.cs
web/Controllers/TenantController.cs
web/Views/Shared/_Layout.cshtml

- Routes now follow the site navigation
- All admin pages start with `/admin`, all landlord pages start with `/landlord`, and property pages start with `/property`
- The lists pages are of the form `/admin/lists/XX`
- Operations on these pages follow this pattern, e.g. `/admin/lists/tenants/import`
- Individual landlords' dashboards are no longer accessible by admins

BNH-193 Make routes more clearly match site navigation

---

BricksAndHearts.UnitTests/ControllerTests/Property/PropertyControllerTests.cs
web/Controllers/PropertyController.cs
web/ViewModels/PropertyInput/PropertyInputModelTenantPreferences.cs
web/Views/Property/PropertyInputForm/TenantPreferences.cshtml
web/wwwroot/css/site.css
web/wwwroot/js/site.js

-Users can no longer submit their preferences without selecting at least one of Single, Couple, Family
-Users no longer have their form page reset to blank if the model is invalid 
-The Single, Couple, Family buttons now style correctly, appearing filled in with colour if the underlying value is true.

BNH-176: Ensuring server-side validation and buttons on tenant preference form page function correctly

---

BricksAndHearts.UnitTests/ControllerTests/Landlord/LandLordControllerUnassignedTests.cs
BricksAndHearts.UnitTests/ControllerTests/Landlord/LandlordControllerTests.cs
BricksAndHearts.UnitTests/ServiceTests/Landlord/LandlordServiceTests.cs
BricksAndHearts.UnitTests/ServiceTests/TestDatabaseFixture.cs
web/Auth/ClaimsTransformer.cs
web/Controllers/LandlordController.cs
web/Database/LandlordDbModel.cs
web/Enums/ApproveLandlordResult.cs
web/Enums/DisableOrEnableLandlordResult.cs
web/Enums/LandlordRegistrationResult.cs
web/Enums/LinkUserWithLandlordResult.cs
web/Migrations/20220822144228_AddDisabledToLandlord.Designer.cs
web/Migrations/20220822144228_AddDisabledToLandlord.cs
web/Services/LandlordService.cs
web/ViewModels/LandlordProfileModel.cs
web/Views/Landlord/Dashboard.cshtml
web/Views/Landlord/Profile.cshtml

[DATABASE UPDATES IN THIS BRANCH}
Admins can disable landlords (and then re-enable them) through the landlord's profile.
Disabled landlords will see the following display instead of their dashboard:
Disabled landlords will be blocked from all other landlord pages, and will not see the landlord nav-bar.

BNH-147 - disable landlords

---

web/Views/Shared/_Layout.cshtml
web/wwwroot/css/site.css

navbar looks the same on desktop
unexpanded on mobile
expanded on mobile
(double navbars in this image, imagine only 1 blue navbar is present if a user is not both a landlord and admin)

Bnh 194 navbar restyling for mobiles

---

web/Services/PropertyService.cs
web/Views/Property/PropertyInputForm/Availability.cshtml
web/Views/Property/PropertyInputForm/TenantPreferences.cshtml
web/Views/Shared/Details/_TenantPreferences.cshtml

- No longer duplicate universal credit
- Occupied state can be selected by the user (useful for single listings)
- Availability doesn't change to draft when editing other parts of the form

BNH-190 Small bug fixes for properties
